### ISSUE TITLE
Trouble with list-subjects CLI command

### ISSUE THREAD

**Issue by earoy** [richford/coinsparse#1]
When I try to find the subjects with tractometry and two behavioral metrics using the command
 `docker compose run coinsparse list-subjects -v FSQ_04 -v WIAT_Complete -d data/combined_tract_profiles.csv data/data_dictionaries_coins data/coins_assessment_data_20210329` 

I get the following message:
 `Traceback (most recent call last):
  File "/opt/conda/bin/coinsparse", line 33, in <module>
    sys.exit(load_entry_point('coinsparse', 'console_scripts', 'coinsparse')())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/coinsparse/coinsparse/coinsparse.py", line 492, in list_subjects
    pheno_subs = _get_variable_info(
  File "/home/coinsparse/coinsparse/coinsparse.py", line 282, in _get_variable_info
    df_data_dict = create_hbn_summary(
  File "/home/coinsparse/coinsparse/coinsparse.py", line 254, in create_hbn_summary
    [
  File "/home/coinsparse/coinsparse/coinsparse.py", line 255, in <listcomp>
    parse_single_xlsx(
  File "/home/coinsparse/coinsparse/coinsparse.py", line 146, in parse_single_xlsx
    coins_path = _get_coins_path(coins_filename, coins_dir)
  File "/home/coinsparse/coinsparse/coinsparse.py", line 23, in _get_coins_path
    return [
IndexError: list index out of range
`

**Comment by richford** [comment]
Weird. Can you verify that the FSQ and WIAT csv files are in `data/coins_assessment_data_20210329`?

**Comment by richford** [comment]
I can confirm that I get an error (although not the same one), when I try this using `docker compose run`, but not when I use the `pip` installed version.

**Comment by richford** [comment]
Okay, the issue was missing data files in the COINS directory. @earoy had the ones he needed but `coinsparse` expected all of them. In [ff47e5](https://github.com/richford/coinsparse/commit/ff47e54460ec7c359114c7b9f3e6b96ea916f7cb) I fixed this so it allows missing files, issues a warning, and allows the user to suppress the warning with `--suppress-warnings`.
